language: node_js

os:
  - osx

node_js:
  - node

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - npm run format
  - npm run lint
  - npm test

notifications:
  email: false